# General stuff
name: Jamie Mansfield
root: /

# Navigation
navigation:
  - title: Home
    url: /

  - title: Blog
    url: /blog/

  - title: About Me
    url: /about/

# Extra plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Disqus
disqus_shortname: jamierocks
