# General stuff
name: Jamie Mansfield
root: /

# Posts
permalink: :year/:month/:day/:title/

# Navigation
navigation:
  - title: Home
    url: /

  - title: Blog
    url: /blog/

  - title: About Me
    url: /about/

# Extra plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# SASS settings
sass:
  style: :compressed

# Disqus
disqus_shortname: jamierocks
