# General stuff
name: Jamie Mansfield
root: /

# Navigation
navigation:
  - title: Home
    url: /

  - title: Blog
    url: /blog/

  - title: About Me
    url: /about/

# Disqus
disqus_shortname: jamierocks
